eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
  error:
    include_message: always
spring:
  application:
    name: gateway_ms
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: students_ms
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/students/**
          - id: schools_ms
            uri: http://localhost:8070
            predicates:
              - Path=/api/v1/schools/**