eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8222
  error:
    include_message: always
spring:
  application:
    name: gateway_ms
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: students_ms
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/students/**
          - id: schools
            uri: http://localhost:8070
            predicates:
              - Path=/api/v1/schools/**

m_c2:
  p3: test_5

management:
  tracing:
    sampling:
      probability: 1.0