eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090
  error:
    include_message: always

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    #      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  datasource:
    driven-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mic_ser_student?createDatabaseIfNotExist=true
    username: root
    password: Temp1234%